import os

env = os.environ.get

OPENAI_API_KEY=env("OPENAI_API_KEY")
PINECONE_API_KEY=env("PINECONE_API_KEY")
PINECONE_ENVIRONMENT=env("PINECONE_ENVIRONMENT")
PINECONE_INDEX_NAME=env("PINECONE_INDEX_NAME")
PINECONE_NAMESPACE=env("PINECONE_INDEX_NAME")

